// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type IdempotencyKey struct {
	CustomerID  string
	Key         string
	TransferID  string
	RequestHash string
	CreatedAt   time.Time
}

type Limit struct {
	Tier     string
	Currency string
	PerTx    int64
	Daily    int64
}

type Outbox struct {
	ID        string
	Topic     string
	Key       string
	Payload   []byte
	CreatedAt time.Time
	SentAt    *time.Time
}

type Rate struct {
	Pair       string
	BuyMicros  int64
	SellMicros int64
	ValidFrom  time.Time
}

type Transfer struct {
	ID                string
	Type              string
	State             string
	CustomerID        string
	FromAccountID     *string
	ToAccountID       *string
	ToAccountNumber   *string
	Amount            int64
	Currency          string
	CounterAmount     *int64
	CounterCurrency   *string
	AppliedRateMicros *int64
	RatePair          *string
	Reason            *string
	HoldID            *string
	RecoveryAttempts  int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type TransferEvent struct {
	ID         int64
	TransferID string
	FromState  string
	ToState    string
	Detail     []byte
	At         time.Time
}
