// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTransferEvent = `-- name: AppendTransferEvent :exec
INSERT INTO transfer_events (transfer_id, from_state, to_state, detail)
VALUES ($1, $2, $3, $4)
`

type AppendTransferEventParams struct {
	TransferID string
	FromState  string
	ToState    string
	Detail     []byte
}

func (q *Queries) AppendTransferEvent(ctx context.Context, arg AppendTransferEventParams) error {
	_, err := q.db.Exec(ctx, appendTransferEvent,
		arg.TransferID,
		arg.FromState,
		arg.ToState,
		arg.Detail,
	)
	return err
}

const claimStuck = `-- name: ClaimStuck :many
WITH stuck AS (
    SELECT id FROM transfers
    WHERE state = ANY($1::text[])
      AND updated_at < now() - $2::interval
    ORDER BY updated_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
UPDATE transfers t
SET recovery_attempts = t.recovery_attempts + 1, updated_at = now()
FROM stuck
WHERE t.id = stuck.id
RETURNING t.id
`

type ClaimStuckParams struct {
	States     []string
	StaleAfter pgtype.Interval
	ClaimLimit int32
}

func (q *Queries) ClaimStuck(ctx context.Context, arg ClaimStuckParams) ([]string, error) {
	rows, err := q.db.Query(ctx, claimStuck, arg.States, arg.StaleAfter, arg.ClaimLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT customer_id, key, transfer_id, request_hash, created_at FROM idempotency_keys WHERE customer_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	CustomerID string
	Key        string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.CustomerID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.CustomerID,
		&i.Key,
		&i.TransferID,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRate = `-- name: GetLatestRate :one
SELECT pair, buy_micros, sell_micros, valid_from FROM rates
WHERE pair = $1 AND valid_from <= $2
ORDER BY valid_from DESC
LIMIT 1
`

type GetLatestRateParams struct {
	Pair      string
	ValidFrom time.Time
}

func (q *Queries) GetLatestRate(ctx context.Context, arg GetLatestRateParams) (Rate, error) {
	row := q.db.QueryRow(ctx, getLatestRate, arg.Pair, arg.ValidFrom)
	var i Rate
	err := row.Scan(
		&i.Pair,
		&i.BuyMicros,
		&i.SellMicros,
		&i.ValidFrom,
	)
	return i, err
}

const getLimit = `-- name: GetLimit :one
SELECT tier, currency, per_tx, daily FROM limits WHERE tier = $1 AND currency = $2
`

type GetLimitParams struct {
	Tier     string
	Currency string
}

func (q *Queries) GetLimit(ctx context.Context, arg GetLimitParams) (Limit, error) {
	row := q.db.QueryRow(ctx, getLimit, arg.Tier, arg.Currency)
	var i Limit
	err := row.Scan(
		&i.Tier,
		&i.Currency,
		&i.PerTx,
		&i.Daily,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, type, state, customer_id, from_account_id, to_account_id, to_account_number, amount, currency, counter_amount, counter_currency, applied_rate_micros, rate_pair, reason, hold_id, recovery_attempts, created_at, updated_at FROM transfers WHERE id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, id string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.State,
		&i.CustomerID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.ToAccountNumber,
		&i.Amount,
		&i.Currency,
		&i.CounterAmount,
		&i.CounterCurrency,
		&i.AppliedRateMicros,
		&i.RatePair,
		&i.Reason,
		&i.HoldID,
		&i.RecoveryAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransfer = `-- name: InsertTransfer :exec
INSERT INTO transfers (id, type, state, customer_id, from_account_id, to_account_id,
                       to_account_number, amount, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertTransferParams struct {
	ID              string
	Type            string
	State           string
	CustomerID      string
	FromAccountID   *string
	ToAccountID     *string
	ToAccountNumber *string
	Amount          int64
	Currency        string
}

func (q *Queries) InsertTransfer(ctx context.Context, arg InsertTransferParams) error {
	_, err := q.db.Exec(ctx, insertTransfer,
		arg.ID,
		arg.Type,
		arg.State,
		arg.CustomerID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.ToAccountNumber,
		arg.Amount,
		arg.Currency,
	)
	return err
}

const listLatestRates = `-- name: ListLatestRates :many
SELECT DISTINCT ON (pair) pair, buy_micros, sell_micros, valid_from
FROM rates
WHERE valid_from <= $1
ORDER BY pair, valid_from DESC
`

func (q *Queries) ListLatestRates(ctx context.Context, validFrom time.Time) ([]Rate, error) {
	rows, err := q.db.Query(ctx, listLatestRates, validFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rate
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.Pair,
			&i.BuyMicros,
			&i.SellMicros,
			&i.ValidFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByCustomer = `-- name: ListTransfersByCustomer :many
SELECT id, type, state, customer_id, from_account_id, to_account_id, to_account_number, amount, currency, counter_amount, counter_currency, applied_rate_micros, rate_pair, reason, hold_id, recovery_attempts, created_at, updated_at FROM transfers
WHERE customer_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTransfersByCustomerParams struct {
	CustomerID string
	CursorTime time.Time
	CursorID   string
	PageLimit  int32
}

func (q *Queries) ListTransfersByCustomer(ctx context.Context, arg ListTransfersByCustomerParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByCustomer,
		arg.CustomerID,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.State,
			&i.CustomerID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.ToAccountNumber,
			&i.Amount,
			&i.Currency,
			&i.CounterAmount,
			&i.CounterCurrency,
			&i.AppliedRateMicros,
			&i.RatePair,
			&i.Reason,
			&i.HoldID,
			&i.RecoveryAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyOutgoing = `-- name: SumDailyOutgoing :one
SELECT COALESCE(sum(amount), 0)::bigint AS total
FROM transfers
WHERE customer_id = $1
  AND currency = $2
  AND type IN ('INTERNAL', 'P2P')
  AND state <> 'FAILED'
  AND created_at >= $3
`

type SumDailyOutgoingParams struct {
	CustomerID string
	Currency   string
	CreatedAt  time.Time
}

func (q *Queries) SumDailyOutgoing(ctx context.Context, arg SumDailyOutgoingParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumDailyOutgoing, arg.CustomerID, arg.Currency, arg.CreatedAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const tryInsertIdempotencyKey = `-- name: TryInsertIdempotencyKey :execrows
INSERT INTO idempotency_keys (customer_id, key, transfer_id, request_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (customer_id, key) DO NOTHING
`

type TryInsertIdempotencyKeyParams struct {
	CustomerID  string
	Key         string
	TransferID  string
	RequestHash string
}

func (q *Queries) TryInsertIdempotencyKey(ctx context.Context, arg TryInsertIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryInsertIdempotencyKey,
		arg.CustomerID,
		arg.Key,
		arg.TransferID,
		arg.RequestHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransferGuarded = `-- name: UpdateTransferGuarded :execrows
UPDATE transfers
SET state               = $2,
    to_account_id       = $3,
    counter_amount      = $4,
    counter_currency    = $5,
    applied_rate_micros = $6,
    rate_pair           = $7,
    reason              = $8,
    hold_id             = $9,
    updated_at          = now()
WHERE id = $1 AND state = $10
`

type UpdateTransferGuardedParams struct {
	ID                string
	State             string
	ToAccountID       *string
	CounterAmount     *int64
	CounterCurrency   *string
	AppliedRateMicros *int64
	RatePair          *string
	Reason            *string
	HoldID            *string
	ExpectedState     string
}

func (q *Queries) UpdateTransferGuarded(ctx context.Context, arg UpdateTransferGuardedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransferGuarded,
		arg.ID,
		arg.State,
		arg.ToAccountID,
		arg.CounterAmount,
		arg.CounterCurrency,
		arg.AppliedRateMicros,
		arg.RatePair,
		arg.Reason,
		arg.HoldID,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
