// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Outbox struct {
	ID        string
	Topic     string
	Key       string
	Payload   []byte
	CreatedAt time.Time
	SentAt    *time.Time
}

type Role struct {
	UserID string
	Role   string
}

type Session struct {
	ID          string
	UserID      string
	FamilyID    string
	RefreshHash []byte
	RotatedFrom *string
	RotatedTo   *string
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	Ip          string
	UserAgent   string
	CreatedAt   time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	Phone        string
	CreatedAt    time.Time
}
