// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addRole = `-- name: AddRole :exec
INSERT INTO roles (user_id, role) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddRoleParams struct {
	UserID string
	Role   string
}

func (q *Queries) AddRole(ctx context.Context, arg AddRoleParams) error {
	_, err := q.db.Exec(ctx, addRole, arg.UserID, arg.Role)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, family_id, refresh_hash, rotated_from, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, family_id, refresh_hash, rotated_from, rotated_to, expires_at, revoked_at, ip, user_agent, created_at
`

type CreateSessionParams struct {
	UserID      string
	FamilyID    string
	RefreshHash []byte
	RotatedFrom *string
	ExpiresAt   time.Time
	Ip          string
	UserAgent   string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.FamilyID,
		arg.RefreshHash,
		arg.RotatedFrom,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshHash,
		&i.RotatedFrom,
		&i.RotatedTo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, phone, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
	Phone        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT role FROM roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) GetRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, family_id, refresh_hash, rotated_from, rotated_to, expires_at, revoked_at, ip, user_agent, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshHash,
		&i.RotatedFrom,
		&i.RotatedTo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, family_id, refresh_hash, rotated_from, rotated_to, expires_at, revoked_at, ip, user_agent, created_at FROM sessions WHERE refresh_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshHash,
		&i.RotatedFrom,
		&i.RotatedTo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, phone, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, phone, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, family_id, refresh_hash, rotated_from, rotated_to, expires_at, revoked_at, ip, user_agent, created_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.RefreshHash,
			&i.RotatedFrom,
			&i.RotatedTo,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionRotated = `-- name: MarkSessionRotated :execrows
UPDATE sessions
SET revoked_at = now(), rotated_to = $2
WHERE id = $1 AND revoked_at IS NULL
`

type MarkSessionRotatedParams struct {
	ID        string
	RotatedTo *string
}

func (q *Queries) MarkSessionRotated(ctx context.Context, arg MarkSessionRotatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionRotated, arg.ID, arg.RotatedTo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE sessions
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionFamily(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, familyID)
	return err
}
