// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type AccountBalance struct {
	AccountID string
	Currency  string
	Balance   int64
	Held      int64
	Version   int64
	UpdatedAt time.Time
}

type Hold struct {
	ID            string
	AccountID     string
	Amount        int64
	Currency      string
	ReferenceType string
	ReferenceID   string
	Status        string
	ExpiresAt     time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type JournalEntriesDefault struct {
	ID            string
	ReferenceType string
	ReferenceID   string
	OccurredAt    time.Time
	CreatedAt     time.Time
}

type JournalEntry struct {
	ID            string
	ReferenceType string
	ReferenceID   string
	OccurredAt    time.Time
	CreatedAt     time.Time
}

type JournalEntryRef struct {
	ReferenceType string
	ReferenceID   string
	EntryID       string
	OccurredAt    time.Time
}

type LedgerAccount struct {
	ID                string
	ExternalAccountID *string
	InternalCode      *string
	Type              string
	Currency          string
	Status            string
	CreatedAt         time.Time
}

type Outbox struct {
	ID        string
	Topic     string
	Key       string
	Payload   []byte
	CreatedAt time.Time
	SentAt    *time.Time
}

type Posting struct {
	ID         string
	EntryID    string
	AccountID  string
	Amount     int64
	Currency   string
	OccurredAt time.Time
}

type PostingsDefault struct {
	ID         string
	EntryID    string
	AccountID  string
	Amount     int64
	Currency   string
	OccurredAt time.Time
}
