// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const getAccountByExternalID = `-- name: GetAccountByExternalID :one
SELECT id, external_account_id, internal_code, type, currency, status, created_at FROM ledger_accounts WHERE external_account_id = $1
`

func (q *Queries) GetAccountByExternalID(ctx context.Context, externalAccountID *string) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByExternalID, externalAccountID)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalAccountID,
		&i.InternalCode,
		&i.Type,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, external_account_id, internal_code, type, currency, status, created_at FROM ledger_accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalAccountID,
		&i.InternalCode,
		&i.Type,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByInternalCode = `-- name: GetAccountByInternalCode :one
SELECT id, external_account_id, internal_code, type, currency, status, created_at FROM ledger_accounts WHERE internal_code = $1
`

func (q *Queries) GetAccountByInternalCode(ctx context.Context, internalCode *string) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByInternalCode, internalCode)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalAccountID,
		&i.InternalCode,
		&i.Type,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBalancesByIDs = `-- name: GetBalancesByIDs :many
SELECT b.account_id, b.currency, b.balance, b.held, b.version, b.updated_at,
       a.external_account_id, a.internal_code
FROM account_balances b
JOIN ledger_accounts a ON a.id = b.account_id
WHERE b.account_id = ANY($1::uuid[])
`

type GetBalancesByIDsRow struct {
	AccountID         string
	Currency          string
	Balance           int64
	Held              int64
	Version           int64
	UpdatedAt         time.Time
	ExternalAccountID *string
	InternalCode      *string
}

func (q *Queries) GetBalancesByIDs(ctx context.Context, dollar_1 []string) ([]GetBalancesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getBalancesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBalancesByIDsRow
	for rows.Next() {
		var i GetBalancesByIDsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Currency,
			&i.Balance,
			&i.Held,
			&i.Version,
			&i.UpdatedAt,
			&i.ExternalAccountID,
			&i.InternalCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, reference_type, reference_id, occurred_at, created_at FROM journal_entries WHERE id = $1 AND occurred_at = $2
`

type GetEntryParams struct {
	ID         string
	OccurredAt time.Time
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, arg.ID, arg.OccurredAt)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEntryPostings = `-- name: GetEntryPostings :many
SELECT p.id, p.entry_id, p.account_id, p.amount, p.currency, p.occurred_at,
       a.external_account_id
FROM postings p
JOIN ledger_accounts a ON a.id = p.account_id
WHERE p.entry_id = $1 AND p.occurred_at = $2
ORDER BY p.id
`

type GetEntryPostingsParams struct {
	EntryID    string
	OccurredAt time.Time
}

type GetEntryPostingsRow struct {
	ID                string
	EntryID           string
	AccountID         string
	Amount            int64
	Currency          string
	OccurredAt        time.Time
	ExternalAccountID *string
}

func (q *Queries) GetEntryPostings(ctx context.Context, arg GetEntryPostingsParams) ([]GetEntryPostingsRow, error) {
	rows, err := q.db.Query(ctx, getEntryPostings, arg.EntryID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntryPostingsRow
	for rows.Next() {
		var i GetEntryPostingsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.ExternalAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryRef = `-- name: GetEntryRef :one
SELECT reference_type, reference_id, entry_id, occurred_at FROM journal_entry_refs WHERE reference_type = $1 AND reference_id = $2
`

type GetEntryRefParams struct {
	ReferenceType string
	ReferenceID   string
}

func (q *Queries) GetEntryRef(ctx context.Context, arg GetEntryRefParams) (JournalEntryRef, error) {
	row := q.db.QueryRow(ctx, getEntryRef, arg.ReferenceType, arg.ReferenceID)
	var i JournalEntryRef
	err := row.Scan(
		&i.ReferenceType,
		&i.ReferenceID,
		&i.EntryID,
		&i.OccurredAt,
	)
	return i, err
}

const getHoldByReference = `-- name: GetHoldByReference :one
SELECT id, account_id, amount, currency, reference_type, reference_id, status, expires_at, created_at, updated_at FROM holds WHERE reference_type = $1 AND reference_id = $2
`

type GetHoldByReferenceParams struct {
	ReferenceType string
	ReferenceID   string
}

func (q *Queries) GetHoldByReference(ctx context.Context, arg GetHoldByReferenceParams) (Hold, error) {
	row := q.db.QueryRow(ctx, getHoldByReference, arg.ReferenceType, arg.ReferenceID)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBalanceRow = `-- name: InsertBalanceRow :exec
INSERT INTO account_balances (account_id, currency)
VALUES ($1, $2)
ON CONFLICT (account_id) DO NOTHING
`

type InsertBalanceRowParams struct {
	AccountID string
	Currency  string
}

func (q *Queries) InsertBalanceRow(ctx context.Context, arg InsertBalanceRowParams) error {
	_, err := q.db.Exec(ctx, insertBalanceRow, arg.AccountID, arg.Currency)
	return err
}

const insertCustomerAccount = `-- name: InsertCustomerAccount :one
INSERT INTO ledger_accounts (external_account_id, type, currency)
VALUES ($1, 'customer', $2)
ON CONFLICT (external_account_id) DO NOTHING
RETURNING id, external_account_id, internal_code, type, currency, status, created_at
`

type InsertCustomerAccountParams struct {
	ExternalAccountID *string
	Currency          string
}

func (q *Queries) InsertCustomerAccount(ctx context.Context, arg InsertCustomerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, insertCustomerAccount, arg.ExternalAccountID, arg.Currency)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.ExternalAccountID,
		&i.InternalCode,
		&i.Type,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO journal_entries (id, reference_type, reference_id, occurred_at)
VALUES ($1, $2, $3, $4)
`

type InsertEntryParams struct {
	ID            string
	ReferenceType string
	ReferenceID   string
	OccurredAt    time.Time
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.Exec(ctx, insertEntry,
		arg.ID,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.OccurredAt,
	)
	return err
}

const insertEntryRef = `-- name: InsertEntryRef :exec
INSERT INTO journal_entry_refs (reference_type, reference_id, entry_id, occurred_at)
VALUES ($1, $2, $3, $4)
`

type InsertEntryRefParams struct {
	ReferenceType string
	ReferenceID   string
	EntryID       string
	OccurredAt    time.Time
}

func (q *Queries) InsertEntryRef(ctx context.Context, arg InsertEntryRefParams) error {
	_, err := q.db.Exec(ctx, insertEntryRef,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.EntryID,
		arg.OccurredAt,
	)
	return err
}

const insertHold = `-- name: InsertHold :exec
INSERT INTO holds (id, account_id, amount, currency, reference_type, reference_id, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertHoldParams struct {
	ID            string
	AccountID     string
	Amount        int64
	Currency      string
	ReferenceType string
	ReferenceID   string
	Status        string
	ExpiresAt     time.Time
}

func (q *Queries) InsertHold(ctx context.Context, arg InsertHoldParams) error {
	_, err := q.db.Exec(ctx, insertHold,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Status,
		arg.ExpiresAt,
	)
	return err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (id, entry_id, account_id, amount, currency, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPostingParams struct {
	ID         string
	EntryID    string
	AccountID  string
	Amount     int64
	Currency   string
	OccurredAt time.Time
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.Exec(ctx, insertPosting,
		arg.ID,
		arg.EntryID,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.OccurredAt,
	)
	return err
}

const listExpiredHolds = `-- name: ListExpiredHolds :many
SELECT id, account_id, amount, currency, reference_type, reference_id, status, expires_at, created_at, updated_at FROM holds
WHERE status = 'active' AND expires_at < now()
ORDER BY expires_at
LIMIT $1
`

func (q *Queries) ListExpiredHolds(ctx context.Context, limit int32) ([]Hold, error) {
	rows, err := q.db.Query(ctx, listExpiredHolds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hold
	for rows.Next() {
		var i Hold
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsPage = `-- name: ListPostingsPage :many
SELECT p.id, p.entry_id, p.account_id, p.amount, p.currency, p.occurred_at,
       a.external_account_id
FROM postings p
JOIN ledger_accounts a ON a.id = p.account_id
WHERE p.account_id = $1
  AND p.occurred_at >= $2
  AND p.occurred_at < $3
  AND (p.occurred_at, p.id) < ($4::timestamptz, $5::uuid)
ORDER BY p.occurred_at DESC, p.id DESC
LIMIT $6
`

type ListPostingsPageParams struct {
	AccountID  string
	FromTime   time.Time
	ToTime     time.Time
	CursorTime time.Time
	CursorID   string
	PageLimit  int32
}

type ListPostingsPageRow struct {
	ID                string
	EntryID           string
	AccountID         string
	Amount            int64
	Currency          string
	OccurredAt        time.Time
	ExternalAccountID *string
}

func (q *Queries) ListPostingsPage(ctx context.Context, arg ListPostingsPageParams) ([]ListPostingsPageRow, error) {
	rows, err := q.db.Query(ctx, listPostingsPage,
		arg.AccountID,
		arg.FromTime,
		arg.ToTime,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostingsPageRow
	for rows.Next() {
		var i ListPostingsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.ExternalAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :one
SELECT account_id, currency, balance, held, version, updated_at FROM account_balances WHERE account_id = $1 FOR UPDATE
`

func (q *Queries) LockBalance(ctx context.Context, accountID string) (AccountBalance, error) {
	row := q.db.QueryRow(ctx, lockBalance, accountID)
	var i AccountBalance
	err := row.Scan(
		&i.AccountID,
		&i.Currency,
		&i.Balance,
		&i.Held,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const lockHoldByID = `-- name: LockHoldByID :one
SELECT id, account_id, amount, currency, reference_type, reference_id, status, expires_at, created_at, updated_at FROM holds WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockHoldByID(ctx context.Context, id string) (Hold, error) {
	row := q.db.QueryRow(ctx, lockHoldByID, id)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setHoldStatus = `-- name: SetHoldStatus :exec
UPDATE holds SET status = $2, updated_at = now() WHERE id = $1
`

type SetHoldStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetHoldStatus(ctx context.Context, arg SetHoldStatusParams) error {
	_, err := q.db.Exec(ctx, setHoldStatus, arg.ID, arg.Status)
	return err
}

const sumPostingsForAccount = `-- name: SumPostingsForAccount :one
SELECT COALESCE(sum(amount), 0)::bigint AS total
FROM postings
WHERE account_id = $1
`

func (q *Queries) SumPostingsForAccount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumPostingsForAccount, accountID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE account_balances
SET balance = $2, held = $3, version = $4, updated_at = now()
WHERE account_id = $1
`

type UpdateBalanceParams struct {
	AccountID string
	Balance   int64
	Held      int64
	Version   int64
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance,
		arg.AccountID,
		arg.Balance,
		arg.Held,
		arg.Version,
	)
	return err
}
