// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Alert struct {
	ID         string
	CustomerID string
	TransferID string
	RuleID     string
	Severity   string
	Details    []byte
	CreatedAt  time.Time
}

type Beneficiary struct {
	CustomerID          string
	CounterpartyAccount string
	FirstSeen           time.Time
}

type CustomerStat struct {
	CustomerID string
	Currency   string
	Day        time.Time
	DayOutSum  int64
	Win5mStart time.Time
	Win5mCount int32
	UpdatedAt  time.Time
}

type Outbox struct {
	ID        string
	Topic     string
	Key       string
	Payload   []byte
	CreatedAt time.Time
	SentAt    *time.Time
}

type ProcessedMessage struct {
	ConsumerGroup string
	EventID       string
	ProcessedAt   time.Time
}

type Rule struct {
	ID       string
	Kind     string
	Params   []byte
	Severity string
	Enabled  bool
}
