// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const countAlerts = `-- name: CountAlerts :one
SELECT count(*) FROM alerts WHERE customer_id = $1
`

func (q *Queries) CountAlerts(ctx context.Context, customerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAlerts, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStats = `-- name: GetStats :one
SELECT customer_id, currency, day, day_out_sum, win5m_start, win5m_count, updated_at FROM customer_stats WHERE customer_id = $1 AND currency = $2
`

type GetStatsParams struct {
	CustomerID string
	Currency   string
}

func (q *Queries) GetStats(ctx context.Context, arg GetStatsParams) (CustomerStat, error) {
	row := q.db.QueryRow(ctx, getStats, arg.CustomerID, arg.Currency)
	var i CustomerStat
	err := row.Scan(
		&i.CustomerID,
		&i.Currency,
		&i.Day,
		&i.DayOutSum,
		&i.Win5mStart,
		&i.Win5mCount,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (id, customer_id, transfer_id, rule_id, severity, details)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAlertParams struct {
	ID         string
	CustomerID string
	TransferID string
	RuleID     string
	Severity   string
	Details    []byte
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.ID,
		arg.CustomerID,
		arg.TransferID,
		arg.RuleID,
		arg.Severity,
		arg.Details,
	)
	return err
}

const listEnabledRules = `-- name: ListEnabledRules :many
SELECT id, kind, params, severity, enabled FROM rules WHERE enabled ORDER BY id
`

func (q *Queries) ListEnabledRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Params,
			&i.Severity,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryInsertBeneficiary = `-- name: TryInsertBeneficiary :execrows
INSERT INTO beneficiaries (customer_id, counterparty_account)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type TryInsertBeneficiaryParams struct {
	CustomerID          string
	CounterpartyAccount string
}

func (q *Queries) TryInsertBeneficiary(ctx context.Context, arg TryInsertBeneficiaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryInsertBeneficiary, arg.CustomerID, arg.CounterpartyAccount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStats = `-- name: UpsertStats :exec
INSERT INTO customer_stats (customer_id, currency, day, day_out_sum, win5m_start, win5m_count, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (customer_id, currency) DO UPDATE
SET day         = EXCLUDED.day,
    day_out_sum = EXCLUDED.day_out_sum,
    win5m_start = EXCLUDED.win5m_start,
    win5m_count = EXCLUDED.win5m_count,
    updated_at  = now()
`

type UpsertStatsParams struct {
	CustomerID string
	Currency   string
	Day        time.Time
	DayOutSum  int64
	Win5mStart time.Time
	Win5mCount int32
}

func (q *Queries) UpsertStats(ctx context.Context, arg UpsertStatsParams) error {
	_, err := q.db.Exec(ctx, upsertStats,
		arg.CustomerID,
		arg.Currency,
		arg.Day,
		arg.DayOutSum,
		arg.Win5mStart,
		arg.Win5mCount,
	)
	return err
}
