// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Account struct {
	ID         string
	CustomerID string
	Number     string
	Currency   string
	Status     string
	OpenedAt   time.Time
}

type Balance struct {
	AccountID string
	Balance   int64
	Version   int64
	AsOf      time.Time
}

type Customer struct {
	ID        string
	UserID    string
	Tier      string
	CreatedAt time.Time
}

type Outbox struct {
	ID        string
	Topic     string
	Key       string
	Payload   []byte
	CreatedAt time.Time
	SentAt    *time.Time
}

type ProcessedMessage struct {
	ConsumerGroup string
	EventID       string
	ProcessedAt   time.Time
}
