// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, customer_id, number, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, customer_id, number, currency, status, opened_at
`

type CreateAccountParams struct {
	ID         string
	CustomerID string
	Number     string
	Currency   string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.CustomerID,
		arg.Number,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Number,
		&i.Currency,
		&i.Status,
		&i.OpenedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT a.id, a.customer_id, a.number, a.currency, a.status, a.opened_at, c.user_id, c.tier
FROM accounts a
JOIN customers c ON c.id = a.customer_id
WHERE a.id = $1
`

type GetAccountByIDRow struct {
	ID         string
	CustomerID string
	Number     string
	Currency   string
	Status     string
	OpenedAt   time.Time
	UserID     string
	Tier       string
}

func (q *Queries) GetAccountByID(ctx context.Context, id string) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Number,
		&i.Currency,
		&i.Status,
		&i.OpenedAt,
		&i.UserID,
		&i.Tier,
	)
	return i, err
}

const getAccountByNumber = `-- name: GetAccountByNumber :one
SELECT a.id, a.customer_id, a.number, a.currency, a.status, a.opened_at, c.user_id, c.tier
FROM accounts a
JOIN customers c ON c.id = a.customer_id
WHERE a.number = $1
`

type GetAccountByNumberRow struct {
	ID         string
	CustomerID string
	Number     string
	Currency   string
	Status     string
	OpenedAt   time.Time
	UserID     string
	Tier       string
}

func (q *Queries) GetAccountByNumber(ctx context.Context, number string) (GetAccountByNumberRow, error) {
	row := q.db.QueryRow(ctx, getAccountByNumber, number)
	var i GetAccountByNumberRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Number,
		&i.Currency,
		&i.Status,
		&i.OpenedAt,
		&i.UserID,
		&i.Tier,
	)
	return i, err
}

const getCustomerByUserID = `-- name: GetCustomerByUserID :one
SELECT id, user_id, tier, created_at FROM customers WHERE user_id = $1
`

func (q *Queries) GetCustomerByUserID(ctx context.Context, userID string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByUserID, userID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT a.id, a.customer_id, a.number, a.currency, a.status, a.opened_at, c.user_id, c.tier
FROM accounts a
JOIN customers c ON c.id = a.customer_id
WHERE c.user_id = $1
ORDER BY a.opened_at
`

type ListAccountsByUserRow struct {
	ID         string
	CustomerID string
	Number     string
	Currency   string
	Status     string
	OpenedAt   time.Time
	UserID     string
	Tier       string
}

func (q *Queries) ListAccountsByUser(ctx context.Context, userID string) ([]ListAccountsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByUserRow
	for rows.Next() {
		var i ListAccountsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Number,
			&i.Currency,
			&i.Status,
			&i.OpenedAt,
			&i.UserID,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts SET status = $2 WHERE id = $1 RETURNING id, customer_id, number, currency, status, opened_at
`

type UpdateAccountStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Number,
		&i.Currency,
		&i.Status,
		&i.OpenedAt,
	)
	return i, err
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO customers (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, tier, created_at
`

func (q *Queries) UpsertCustomer(ctx context.Context, userID string) (Customer, error) {
	row := q.db.QueryRow(ctx, upsertCustomer, userID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}
